#!/bin/bash

PROG=./sd3
PARAMS="-bkz -beta40 -o/dev/null"
DIR=Tests

# Colors
BAD='\033[1;33m'
GOOD='\033[0;32m'
NC='\033[0m'

############### Test files ###############################
FILESQUICK="KM_Id7_t2_k3.in,30
KM_Id9_t2_k3.txt,840
in_sd.txt,25
in_sd2.txt,3
mendelsohn.txt,1829
eqs,16
KM_PSL_2_23_7_8.in,2
n8_282.txt,104
unitals_v1.txt,78
4-arcs.txt,32708"
###############          #################################
# FILESLONG="KM_PGGL_2_32_t7_k8.in,4996426
# n8_279.txt,1848
# unitals_v2.txt,78"
##########################################################

function run_code {
    echo $PROG $PARAMS $DIR/$1
    numsolutions=`$PROG $PARAMS $DIR/$1 2>/dev/null | awk 'BEGIN { s=0 } { s+=1; } END { print s }'`
    if [[ "$numsolutions" == "$2" ]]; then
        echo -e "\t${GOOD}CORRECT${NC} $1: $numsolutions solutions"
    else
        echo -e "\t${BAD}!!!!!!!!! FAILURE $1: $numsolutions solutions${NC}"
    fi
}

for f in $FILESQUICK ; do
    # Split pairs: filename / number of solutions
    OLDIFS=$IFS; IFS=','; set -- $f; IFS=$OLDIFS
    run_code $1 $2
done